[package]
name = "rufy_core"
version = "0.1.0"
authors = ["Nikita <nikitadiscore@gmail.com>"]
edition = "2018"

[dependencies]
rlua = "0.17.0"
walkdir = "2"
tokio = { version = "1", features = ["sync", "rt"] }
sdl2 = "0.34.3"