[package]
name = "rufy_engine"
version = "0.1.0"
authors = ["Nikita <nikitadiscore@gmail.com>"]
edition = "2018"

[dependencies]
"rufy_core" = { path = "../rufy_core" }
tokio = { version = "1", features = ["rt"] }
sdl2 = "0.34.3"